//! Print the driver compatibility matrix as Markdown.
//!
//! ```text
//! cargo run -p branchyard-harness --example compat_matrix > docs/compatibility.md
//! ```
//!
//! Rows come from `profiles::PROFILES`, `profiles::NOT_IMPLEMENTED` and the
//! harnesses in `branchyard_controls::harness`; live results come
//! from the reports in `docs/qualification/`. A test in
//! `tests/compatibility.rs` fails when the committed file is stale.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use branchyard_controls::harness::HARNESSES;
use branchyard_harness::profiles::{self, Protocol, NOT_IMPLEMENTED, PROFILES};
use serde_json::Value;

/// A profile's live qualification, from its report.
struct Qualified {
    file: String,
    passed: usize,
    total: usize,
    date: String,
    version: String,
}

fn qualifications() -> BTreeMap<String, Qualified> {
    let directory = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/qualification");
    let mut files: Vec<_> = fs::read_dir(&directory)
        .unwrap_or_else(|e| panic!("{}: {e}", directory.display()))
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.extension().is_some_and(|e| e == "json"))
        .collect();
    files.sort();
    let mut reports = BTreeMap::new();
    for path in files {
        let report: Value = serde_json::from_str(&fs::read_to_string(&path).unwrap())
            .unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        let profile = report["profile"].as_str().unwrap_or_default().to_owned();
        assert!(
            profiles::by_id(&profile).is_some(),
            "{} reports unknown profile {profile:?}",
            path.display()
        );
        let scenarios = report["scenarios"].as_array().cloned().unwrap_or_default();
        let qualified = Qualified {
            file: path.file_name().unwrap().to_string_lossy().into_owned(),
            passed: scenarios.iter().filter(|s| s["passed"] == true).count(),
            total: scenarios.len(),
            date: report["date"].as_str().unwrap_or("undated").to_owned(),
            version: report["harness_version"]
                .as_str()
                .unwrap_or("unknown")
                .to_owned(),
        };
        let file = qualified.file.clone();
        assert!(
            reports.insert(profile.clone(), qualified).is_none(),
            "two reports for {profile}; keep one per profile ({file})"
        );
    }
    reports
}

fn protocol(protocol: Protocol) -> &'static str {
    match protocol {
        Protocol::ClaudeStreamJson => "Claude stream-json",
        Protocol::CodexAppServer => "Codex App Server",
        Protocol::Acp => "ACP v1",
    }
}

fn yes(value: bool) -> &'static str {
    if value {
        "yes"
    } else {
        "no"
    }
}

/// The matrix as Markdown.
pub fn render() -> String {
    let qualified = qualifications();
    let mut out = String::from(
        "# Compatibility\n\
         \n\
         <!-- Generated by `cargo run -p branchyard-harness --example compat_matrix > docs/compatibility.md`. Do not edit. -->\n\
         \n\
         Every integration target and driver profile, in the order of the harness registry. Implemented means the driver exists and passes its protocol tests; it does not mean supported. Live qualification ran the profile's driver against the real harness binary as a local process, not inside a Branchyard sandbox, so isolation, credentials and recovery remain unqualified for every profile. See [driver qualification](qualification/README.md) for scope and findings, and [writing a driver](writing-a-driver.md) to add a row.\n\
         \n\
         Capabilities are what the driver offers before negotiation. ACP resume is used only when the agent advertises `session/resume` or `session/load`; a session that cannot resume fails to open rather than starting fresh. \"Checked against\" names the harness version whose transcript or generated schema the driver's frames were compared with.\n\
         \n\
         | Harness | Profile | Protocol | Role | Resume | Fork | Cancel | Approvals | Usage | Checked against | Live qualification |\n\
         |---|---|---|---|---|---|---|---|---|---|---|\n",
    );
    // Integration targets, then any other registered harness with a profile.
    let rows = HARNESSES
        .iter()
        .filter(|h| h.target.is_some() || PROFILES.iter().any(|p| p.harness == h.id));
    for target in rows {
        let name = format!("{} (`{}`)", target.target.unwrap_or(target.id), target.id);
        let mut implemented = PROFILES
            .iter()
            .filter(|p| p.harness == target.id)
            .peekable();
        if implemented.peek().is_none() {
            let reason = NOT_IMPLEMENTED
                .iter()
                .find(|(id, _)| *id == target.id)
                .map(|(_, reason)| *reason)
                .unwrap_or_else(|| panic!("{} is neither implemented nor explained", target.id));
            out += &format!(
                "| {name} | — | — | — | — | — | — | — | — | — | not implemented: {} |\n",
                reason.replace('|', "\\|")
            );
            continue;
        }
        for (index, profile) in implemented.enumerate() {
            let capabilities = profile.driver().capabilities();
            let resume = match (capabilities.resume, profile.protocol) {
                (true, Protocol::Acp) => "if advertised",
                (resume, _) => yes(resume),
            };
            let live = match qualified.get(profile.id) {
                Some(q) => format!(
                    "[{} of {} pass](qualification/{}), {}, {}",
                    q.passed, q.total, q.file, q.date, q.version
                ),
                None => "not qualified".into(),
            };
            out += &format!(
                "| {name} | `{}` | {} | {} | {resume} | {} | {} | {} | {} | {} | {live} |\n",
                profile.id,
                protocol(profile.protocol),
                if index == 0 { "default" } else { "alternate" },
                yes(capabilities.fork),
                yes(capabilities.cancellation),
                yes(capabilities.tool_approvals),
                yes(capabilities.usage),
                profile.checked_against.unwrap_or("—"),
            );
        }
    }
    out
}

fn main() {
    print!("{}", render());
}
