//! `deploy`: a Docker Compose deployment of the server behind PostgreSQL.

use serde_json::json;

use super::join;
use super::server::{credential, token_file, SCOPES};
use crate::interview::{Answers, Choice, Kind, Question, Rule};
use crate::plan::{ArtifactKind, Plan, PlannedFile};
use crate::probe::{Entropy, Facts, Probe};
use crate::Topic;

pub fn questions(facts: &Facts, _answers: &Answers) -> Vec<Question> {
    vec![
        Question::new(
            "dir",
            Kind::Path,
            "Directory",
            "Where should the deployment files go?",
            "compose.yaml, server.json and a git-ignored secrets/ directory are written there.",
        )
        .default("deploy/branchyard")
        .choices(vec![Choice::new("deploy/branchyard", "deploy/branchyard", "in this repository")]),
        Question::new(
            "repo_path",
            Kind::Path,
            "Repository",
            "Which repository should the server serve (an absolute path on the Docker host)?",
            "Mounted into the container at /repos/NAME.",
        )
        .default(facts.git.as_ref().map(|g| g.root.clone()).unwrap_or_else(|| facts.root.clone()))
        .choices(vec![Choice::new(facts.root.as_str(), "This repository", facts.root.as_str())]),
        Question::new(
            "image",
            Kind::Text,
            "Image",
            "Which server image?",
            "Build it from a Branchyard checkout: docker build -f deploy/Dockerfile -t branchyard-server .",
        )
        .default("branchyard-server:latest")
        .choices(vec![Choice::new("branchyard-server:latest", "branchyard-server:latest", "built locally")]),
        Question::new(
            "port",
            Kind::Number,
            "Port",
            "Which host port should reach the server (published on 127.0.0.1 only)?",
            "The server listens on the compose network; only loopback on the host is published.",
        )
        .default(8421)
        .choices(vec![Choice::new(8421, "8421", "the default")])
        .rule(Rule::Min { value: 1.0 })
        .rule(Rule::Max { value: 65535.0 })
        .rule(Rule::Integer),
    ]
}

pub fn plan(
    facts: &Facts,
    answers: &Answers,
    probe: &dyn Probe,
    entropy: &mut dyn Entropy,
) -> Plan {
    let text = |id: &str, default: &str| super::text(answers, id).unwrap_or_else(|| default.into());
    let dir = text("dir", "deploy/branchyard");
    let repo = facts.repo_name();
    let port = super::float(answers, "port").unwrap_or(8421.0) as u32;
    let secrets = join(&dir, "secrets");
    let mut plan = Plan::new(Topic::Deploy);
    let token_path = join(&secrets, "admin.token");
    let (token, hash) = token_file(&token_path, probe, entropy);
    plan.files.push(token);
    let password_path = join(&secrets, "db-password.txt");
    let (password, _) = token_file(&password_path, probe, entropy);
    plan.files.push(password);
    plan.files.push(PlannedFile::new(
        &join(&secrets, ".gitignore"),
        ArtifactKind::Text,
        0o644,
        "# Generated by `by init deploy`: never commit these.\n*\n".into(),
        probe.read(&join(&secrets, ".gitignore")),
    ));
    let scopes: Vec<String> = SCOPES.iter().map(|s| s.to_string()).collect();
    let config = json!({
        "listen": "0.0.0.0:8421",
        "data_dir": "/data",
        "repos": { repo.clone(): format!("/repos/{repo}") },
        "credentials": [credential(&hash, "admin", "default", &scopes)],
        "max_running": 8,
    });
    let mut body = serde_json::to_string_pretty(&config).expect("JSON serializes");
    body.push('\n');
    let server_path = join(&dir, "server.json");
    let mut server = PlannedFile::new(
        &server_path,
        ArtifactKind::ServerConfig,
        0o644,
        body,
        probe.read(&server_path),
    );
    server.serve_flags = vec!["--insecure-bind".into()];
    plan.files.push(server);
    let compose = format!(
        "# Written by `by init deploy`: `by serve` behind PostgreSQL. See docs/deploy.md.\n\
         # Secrets are files in ./secrets (0600, git-ignored), never variables.\n\
         # The server listens on the compose network; only 127.0.0.1:{port} is published.\n\
         # --insecure-bind: put a TLS-terminating proxy in front before exposing it further.\n\
         services:\n\
         \x20 database:\n\
         \x20   image: postgres:16\n\
         \x20   environment:\n\
         \x20     POSTGRES_DB: branchyard\n\
         \x20     POSTGRES_USER: branchyard\n\
         \x20     POSTGRES_PASSWORD_FILE: /run/secrets/db_password\n\
         \x20   volumes:\n\
         \x20     - branchyard-database:/var/lib/postgresql/data\n\
         \x20   secrets:\n\
         \x20     - db_password\n\
         \x20   healthcheck:\n\
         \x20     test: [\"CMD-SHELL\", \"pg_isready -U branchyard -d branchyard\"]\n\
         \x20     interval: 5s\n\
         \x20     timeout: 5s\n\
         \x20     retries: 12\n\
         \x20 server:\n\
         \x20   image: {image}\n\
         \x20   entrypoint: [\"/bin/sh\", \"-c\"]\n\
         \x20   command:\n\
         \x20     - >\n\
         \x20       exec by serve --config /config/server.json --insecure-bind\n\
         \x20       --database \"postgres://branchyard:$$(cat /run/secrets/db_password)@database:5432/branchyard\"\n\
         \x20   ports:\n\
         \x20     - \"127.0.0.1:{port}:8421\"\n\
         \x20   volumes:\n\
         \x20     - ./server.json:/config/server.json:ro\n\
         \x20     - {repo_path}:/repos/{repo}\n\
         \x20     - branchyard-data:/data\n\
         \x20   secrets:\n\
         \x20     - db_password\n\
         \x20   depends_on:\n\
         \x20     database:\n\
         \x20       condition: service_healthy\n\
         \x20   # SIGTERM gives running operations shutdown_grace_seconds (60); docker\n\
         \x20   # stop must wait longer than that before it kills the server.\n\
         \x20   stop_grace_period: 75s\n\
         \x20   healthcheck:\n\
         \x20     test: [\"CMD\", \"curl\", \"-fsS\", \"http://127.0.0.1:8421/healthz\"]\n\
         \x20     interval: 10s\n\
         \x20     timeout: 3s\n\
         \x20     retries: 3\n\
         \x20     start_period: 5s\n\
         volumes:\n\
         \x20 branchyard-database:\n\
         \x20 branchyard-data:\n\
         secrets:\n\
         \x20 db_password:\n\
         \x20   file: ./secrets/db-password.txt\n",
        image = text("image", "branchyard-server:latest"),
        repo_path = text("repo_path", &facts.root),
    );
    let compose_path = join(&dir, "compose.yaml");
    plan.files.push(PlannedFile::new(
        &compose_path,
        ArtifactKind::Compose,
        0o644,
        compose,
        probe.read(&compose_path),
    ));
    plan.summary.push(format!(
        "Compose deployment in {dir}: {repo} served on 127.0.0.1:{port} behind PostgreSQL 16"
    ));
    plan.summary.push(format!(
        "Client token (0600, printed nowhere): {token_path}"
    ));
    plan.command(
        "docker build -f deploy/Dockerfile -t branchyard-server .",
        "In a Branchyard checkout: build the server image.",
    );
    plan.command(
        format!("docker compose -f {compose_path} up -d"),
        "Start the database and the server.",
    );
    plan.command(
        format!("by --remote http://127.0.0.1:{port} --token-file {token_path} ls"),
        "Reach it as a client.",
    );
    plan
}
