#!/usr/bin/env python3
"""Documentation facts derived from the code, not typed by hand.

Counts, lists and matrices that the code already knows (how many files are
vendored, which crates exist, how many tests there are, which environment
prefixes the runtime strips, which routes the server registers) are computed
here from the source of truth and written in two places:

- docs/facts.json, the full set, committed so a change shows in review;
- every Markdown region marked <!-- fact:NAME -->...<!-- /fact --> (a marker
  directly after a backtick is documentation of the syntax and is skipped),
  whose text is replaced by the fact's rendering.

    python3 tools/docs_facts.py --write   recompute and rewrite both
    python3 tools/docs_facts.py --check   fail on any difference (CI)

--check also fails when a server route is mentioned in neither docs/server.md
nor docs/surfaces.md,
unless tools/docs_facts_allow.txt lists it. That list is a ratchet: an entry
that has become documented must be removed, so it only ever shrinks.

Tables generated by Rust keep their own freshness tests (docs/compatibility.md
by `cargo test -p branchyard-harness`, catalog/*.toml by
`cargo test -p branchyard-controls catalog`); see CONTRIBUTING.md.
No network, no build: everything here is read from files.
"""
import argparse
import json
import re
import sys
import tomllib
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FACTS = ROOT / "docs" / "facts.json"
ALLOW = ROOT / "tools" / "docs_facts_allow.txt"
REGION = re.compile(r"(?<!`)<!-- fact:([A-Za-z0-9_.-]+) -->(.*?)<!-- /fact -->", re.S)
TEST = re.compile(r"^[ \t]*#\[(?:tokio::)?test(?:\([^\n]*\))?\]", re.M)
IGNORE = re.compile(r"^[ \t]*#\[ignore\b", re.M)
ROUTE = re.compile(r'\.route\(\s*"([^"]+)"')
METHODS = re.compile(r"\b(get|post|put|patch|delete)\(")


def markdown_files():
    return sorted(ROOT.glob("*.md")) + sorted((ROOT / "docs").rglob("*.md"))


def rust_files(directory):
    return sorted(p for p in directory.rglob("*.rs") if "target" not in p.parts)


def workspace_crates():
    cargo = tomllib.loads((ROOT / "Cargo.toml").read_text())
    crates = []
    for member in cargo["workspace"]["members"]:
        manifest = tomllib.loads((ROOT / member / "Cargo.toml").read_text())
        crates.append({"name": manifest["package"]["name"], "path": member})
    return sorted(crates, key=lambda c: c["name"])


def vendor_facts():
    lock = json.loads((ROOT / "vendor.lock.json").read_text())
    by_source = Counter(entry["path"].split("/")[1] for entry in lock["files"])
    patches = json.loads((ROOT / "vendor.patches.json").read_text()).get("patches", [])
    return {
        "files": len(lock["files"]),
        "by_source": dict(sorted(by_source.items())),
        "patched": len(patches),
    }


def test_facts(crates):
    per_crate = {}
    for crate in crates:
        tests = ignored = 0
        for directory in ("src", "tests"):
            for path in rust_files(ROOT / crate["path"] / directory):
                text = path.read_text(errors="replace")
                tests += len(TEST.findall(text))
                ignored += len(IGNORE.findall(text))
        per_crate[crate["name"]] = {"tests": tests, "ignored": ignored}
    return {
        "total": sum(c["tests"] for c in per_crate.values()),
        "ignored": sum(c["ignored"] for c in per_crate.values()),
        "by_crate": per_crate,
    }


def http_facts():
    routes = set()
    for path in rust_files(ROOT / "crates" / "branchyard-server" / "src"):
        routes.update(ROUTE.findall(path.read_text(errors="replace")))
    return {"route_count": len(routes), "routes": sorted(routes)}


def runtime_facts():
    text = (ROOT / "crates/branchyard-runtime/src/lib.rs").read_text()
    match = re.search(r"const DEFAULT_STRIP: \[&str; \d+\] = \[(.*?)\];", text, re.S)
    if not match:
        raise SystemExit("docs_facts: DEFAULT_STRIP not found in branchyard-runtime")
    return {"strip_prefixes": re.findall(r'"([^"]+)"', match.group(1))}


def compute():
    crates = workspace_crates()
    return {
        "_comment": "Generated by tools/docs_facts.py --write. Do not edit.",
        "workspace": {"crate_count": len(crates), "crates": [c["name"] for c in crates]},
        "vendor": vendor_facts(),
        "tests": test_facts(crates),
        "http": http_facts(),
        "runtime": runtime_facts(),
    }


def join_and(items):
    return items[0] if len(items) == 1 else ", ".join(items[:-1]) + " and " + items[-1]


def regions(facts):
    """Every region name the Markdown may use, with its exact rendering."""
    vendor, tests = facts["vendor"], facts["tests"]
    by_crate = [
        f"{count['tests']} in `{name}`"
        for name, count in tests["by_crate"].items()
        if count["tests"]
    ]
    return {
        "vendor.files": str(vendor["files"]),
        "vendor.sources": join_and([f"{n} from {s}" for s, n in vendor["by_source"].items()]),
        "vendor.scion": str(vendor["by_source"]["scion"]),
        "vendor.patched": str(vendor["patched"]),
        "workspace.crate_count": str(facts["workspace"]["crate_count"]),
        "tests.total": str(tests["total"]),
        "tests.ignored": str(tests["ignored"]),
        "tests.by_crate": join_and(by_crate),
        "http.route_count": str(facts["http"]["route_count"]),
        "runtime.strip_prefixes": join_and([f"`{p}*`" for p in facts["runtime"]["strip_prefixes"]]),
    }


def rewrite(text, rendered, problems, name):
    def swap(match):
        key = match.group(1)
        if key not in rendered:
            problems.append(f"{name}: unknown fact region '{key}'")
            return match.group(0)
        return f"<!-- fact:{key} -->{rendered[key]}<!-- /fact -->"

    return REGION.sub(swap, text)


def normalise(path):
    return re.sub(r"\{[^}/]*\}|:[A-Za-z_]+", "{}", path)


def route_documented(route, lines):
    """The route, in full or abbreviated (`/deny` after `…/allow`), is in the text."""
    full = normalise(route)
    short = re.sub(r"^/v1/repos/\{\}", "", full)
    parent, _, leaf = full.rpartition("/")
    parent_short = re.sub(r"^/v1/repos/\{\}", "", parent)
    for line in lines:
        if full in line or (short != full and short in line):
            return True
        if leaf and not leaf.startswith("{"):
            abbreviated = re.search(r"(?:/|…/)" + re.escape(leaf) + r"(?![\w-])", line)
            if abbreviated and (parent in line or (parent_short and parent_short in line)):
                return True
    return False


def coverage(facts):
    """Server routes in neither docs/server.md nor docs/surfaces.md, less the ratchet allowlist."""
    doc = "\n".join((ROOT / "docs" / name).read_text() for name in ("server.md", "surfaces.md"))
    lines = normalise(doc.replace("...", "…")).splitlines()
    missing = {r for r in facts["http"]["routes"] if not route_documented(r, lines)}
    allowed = set()
    if ALLOW.exists():
        allowed = {
            line.strip() for line in ALLOW.read_text().splitlines()
            if line.strip() and not line.startswith("#")
        }
    problems = []
    for route in sorted(missing - allowed):
        problems.append(f"route {route} is documented in neither docs/server.md nor docs/surfaces.md")
    for route in sorted(allowed - missing):
        problems.append(
            f"tools/docs_facts_allow.txt lists {route}, which is documented or gone now; remove it"
        )
    return problems


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="rewrite docs/facts.json and every fact region")
    mode.add_argument("--check", action="store_true", help="fail when either differs from the code")
    args = parser.parse_args()

    facts = compute()
    rendered = regions(facts)
    wanted = json.dumps(facts, indent=2) + "\n"
    problems = []
    used = set()

    if args.write:
        FACTS.write_text(wanted)
    elif not FACTS.exists() or FACTS.read_text() != wanted:
        problems.append("docs/facts.json is stale; run python3 tools/docs_facts.py --write")

    for path in markdown_files():
        name = path.relative_to(ROOT).as_posix()
        text = path.read_text()
        used.update(m.group(1) for m in REGION.finditer(text))
        updated = rewrite(text, rendered, problems, name)
        if updated == text:
            continue
        if args.write:
            path.write_text(updated)
        else:
            problems.append(f"{name}: a generated fact was edited by hand or is stale; "
                            "run python3 tools/docs_facts.py --write")

    if args.check:
        problems += coverage(facts)
    if problems:
        sys.exit("docs facts differ from the code:\n" + "\n".join(f"  {p}" for p in problems))
    print(f"docs facts: {len(rendered)} fact kinds, {len(used)} used in the Markdown, "
          f"{facts['http']['route_count']} routes checked.")


if __name__ == "__main__":
    main()
