// Prints crates/branchyard-server/src/companion/qr_fixtures.rs: QR matrices
// made by an independent encoder (Kazuhiko Arase's QRCode for JavaScript,
// MIT, as vendored by the qrcode-terminal package npm itself ships), for
// the pairing link encoder's tests to compare against. Nothing is vendored
// into Branchyard: only these matrices are kept.
//
//   node tools/qr_crosscheck.js > crates/branchyard-server/src/companion/qr_fixtures.rs
//
// QRCODE_VENDOR overrides where the encoder is found.
const path = require('path');
const { execSync } = require('child_process');
const vendor = process.env.QRCODE_VENDOR || path.join(
  execSync('npm root -g').toString().trim(),
  'npm', 'node_modules', 'qrcode-terminal', 'vendor', 'QRCode');
const QRCode = require(path.join(vendor, 'index.js'));
const M = require(path.join(vendor, 'QRErrorCorrectLevel.js')).M;

const cases = [
  ['HELLO', 1, 0],
  ['https://by.example/app/#pair=abc', 3, 2],
  ['https://by.example.com:8421/app/#pair=0123456789abcdef0123456789abcdef', 5, 5],
  ['http://127.0.0.1:8421/app/#pair=0123456789abcdef0123456789abcdef0123456789abcdef', 6, 3],
  ['https://branchyard.internal.example.org:8421/app/#pair=' + 'z'.repeat(64), 7, 6],
  ['x'.repeat(200), 10, 7],
];

let out = '//! QR matrices from an independent encoder, for `qr.rs`\'s tests.\n' +
  '//! Generated by `node tools/qr_crosscheck.js`; do not edit.\n\n' +
  '/// (text, version, mask, rows of `#` dark and `.` light)\n' +
  'pub const FIXTURES: &[(&str, usize, usize, &str)] = &[\n';
for (const [text, version, mask] of cases) {
  const qr = new QRCode(version, M);
  qr.addData(text);
  qr.makeImpl(false, mask);
  const n = qr.getModuleCount();
  let rows = '';
  for (let y = 0; y < n; y++) {
    for (let x = 0; x < n; x++) rows += qr.isDark(y, x) ? '#' : '.';
    rows += '\\n';
  }
  out += `    (\n        ${JSON.stringify(text)},\n        ${version},\n        ${mask},\n        "${rows}",\n    ),\n`;
}
out += '];\n';
process.stdout.write(out);
